image: python:alpine

before_script:
  - apt update && apt install git
  - pip install mkdocs mkdocs-material pygments pymdown-extensions
  - pip install awscli

publish:
  only:
    - master
  script:
    - mkdocs build
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://docs.hypha.earth
    - aws s3 sync ./site s3://docs.hypha.earth
