site_name: Hypha Docs
theme:
  name: 'material'
nav:
  - Home: index.md
  - Membership: membership.md
  - Profiles: profiles.md
  - Proposals: proposals.md
  = Test Net: test-net.md
  - Tech Docs: tech-docs.md
